
import { WeaponType, WeaponConfig, WeaponEffect, TextureStyle } from './types';

export const SCALE_FACTOR = 5.0; 

export const DEFAULT_CONFIG: WeaponConfig = {
  type: WeaponType.SWORD,
  handleLength: 0.3,
  handleRadius: 0.03,
  guardWidth: 0.3,
  bladeLength: 1.0,
  bladeWidth: 0.1,
  bladeThickness: 0.02,
  pommelSize: 0.05,
  handleColor: '#3e2723',
  metalColor: '#cfd8dc',
  guardColor: '#ffd54f',
  roughness: 0.3,
  metalness: 0.8,
  handleTexture: TextureStyle.LEATHER,
  bladeTexture: TextureStyle.NONE,
  effect: WeaponEffect.NONE,
  effectColor: '#ff6b00',
  variant: 'standard'
};

export const PRESETS: Record<string, WeaponConfig> = {
  "Knight's Standard": { 
      ...DEFAULT_CONFIG,
      handleTexture: TextureStyle.LEATHER,
      bladeTexture: TextureStyle.NONE
  },
  "The Old Angler": {
    type: WeaponType.FISHING_POLE,
    handleLength: 0.4, // Cork Grip
    handleRadius: 0.025,
    guardWidth: 0.08, // Reel Size
    bladeLength: 1.8, // Rod Length
    bladeWidth: 0.6, // Line Length hanging down
    bladeThickness: 0.005, // Line Thickness
    pommelSize: 0.04, // Bobber Size
    handleColor: '#d7ccc8', // Cork
    metalColor: '#263238', // Dark Rod
    guardColor: '#d32f2f', // Red Bobber
    roughness: 0.6,
    metalness: 0.4,
    effect: WeaponEffect.NONE,
    effectColor: '#ffffff',
    handleTexture: TextureStyle.WOOD,
    bladeTexture: TextureStyle.NONE
  },
  "Lumberjack Shirt": {
    type: WeaponType.SHIRT,
    handleLength: 0.52, // Torso Length
    handleRadius: 0.3, // Torso Radius
    guardWidth: 0.1, // Sleeve Radius
    bladeLength: 0.3, // Sleeve Length
    bladeWidth: 0.1, 
    bladeThickness: 0.02,
    pommelSize: 0.0,
    handleColor: '#a91b1b', // Red
    metalColor: '#e5b700', // Yellow stripes
    guardColor: '#000000',
    roughness: 0.9,
    metalness: 0.0,
    effect: WeaponEffect.NONE,
    effectColor: '#ffffff',
    handleTexture: TextureStyle.CLOTH, // Plaid
    bladeTexture: TextureStyle.NONE
  },
  "Phoenix Blade": {
    ...DEFAULT_CONFIG,
    metalColor: '#4e342e',
    guardColor: '#bf360c',
    effect: WeaponEffect.FIRE,
    effectColor: '#ff5722',
    handleTexture: TextureStyle.SCALES,
    bladeTexture: TextureStyle.DAMASCUS
  },
  "Storm Arrow": {
    type: WeaponType.ARROW,
    handleLength: 0.7,
    handleRadius: 0.01,
    guardWidth: 0.05,
    bladeLength: 0.1,
    bladeWidth: 0.03,
    bladeThickness: 0.01,
    pommelSize: 0.0,
    handleColor: '#3e2723',
    metalColor: '#eceff1',
    guardColor: '#90a4ae',
    roughness: 0.5,
    metalness: 0.1,
    effect: WeaponEffect.LIGHTNING,
    effectColor: '#00e5ff',
    handleTexture: TextureStyle.WOOD,
    bladeTexture: TextureStyle.COSMIC
  },
  "Dragon Arrow": {
    type: WeaponType.ARROW,
    handleLength: 0.7,
    handleRadius: 0.01,
    guardWidth: 0.05,
    bladeLength: 0.15,
    bladeWidth: 0.04,
    bladeThickness: 0.01,
    pommelSize: 0.0,
    handleColor: '#212121',
    metalColor: '#d84315',
    guardColor: '#ffab00',
    roughness: 0.4,
    metalness: 0.6,
    effect: WeaponEffect.FIRE,
    effectColor: '#ff3d00',
    handleTexture: TextureStyle.WOOD,
    bladeTexture: TextureStyle.SCALES
  },
  "Frost Arrow": {
    type: WeaponType.ARROW,
    handleLength: 0.7,
    handleRadius: 0.01,
    guardWidth: 0.05,
    bladeLength: 0.12,
    bladeWidth: 0.035,
    bladeThickness: 0.01,
    pommelSize: 0.0,
    handleColor: '#e3f2fd',
    metalColor: '#81d4fa',
    guardColor: '#b3e5fc',
    roughness: 0.3,
    metalness: 0.5,
    effect: WeaponEffect.FROST,
    effectColor: '#e0f7fa',
    handleTexture: TextureStyle.WOOD,
    bladeTexture: TextureStyle.NONE
  },
  "Poison Arrow": {
    type: WeaponType.ARROW,
    handleLength: 0.7,
    handleRadius: 0.01,
    guardWidth: 0.05,
    bladeLength: 0.1,
    bladeWidth: 0.03,
    bladeThickness: 0.01,
    pommelSize: 0.0,
    handleColor: '#43a047', // Brighter green for visibility
    metalColor: '#4caf50',
    guardColor: '#2e7d32',
    roughness: 0.8,
    metalness: 0.1,
    effect: WeaponEffect.POISON,
    effectColor: '#76ff03',
    handleTexture: TextureStyle.WOOD,
    bladeTexture: TextureStyle.RUST
  },
  "Mud Arrow": {
    type: WeaponType.ARROW,
    handleLength: 0.7,
    handleRadius: 0.01,
    guardWidth: 0.05,
    bladeLength: 0.1,
    bladeWidth: 0.04,
    bladeThickness: 0.015,
    pommelSize: 0.0,
    handleColor: '#3e2723',
    metalColor: '#5d4037',
    guardColor: '#4e342e',
    roughness: 1.0,
    metalness: 0.0,
    effect: WeaponEffect.MUD,
    effectColor: '#3e2723',
    handleTexture: TextureStyle.WOOD,
    bladeTexture: TextureStyle.RUST
  },
  "Dwarven Axe": {
    type: WeaponType.AXE,
    handleLength: 0.7,
    handleRadius: 0.04,
    guardWidth: 0.1,
    bladeLength: 0.4,
    bladeWidth: 0.3,
    bladeThickness: 0.05,
    pommelSize: 0.06,
    handleColor: '#4e342e',
    metalColor: '#546e7a',
    guardColor: '#546e7a',
    roughness: 0.4,
    metalness: 0.7,
    effect: WeaponEffect.NONE,
    effectColor: '#ffffff',
    handleTexture: TextureStyle.WOOD,
    bladeTexture: TextureStyle.RUST
  },
  "Royal Halberd": {
    type: WeaponType.AXE,
    handleLength: 1.8,
    handleRadius: 0.025,
    guardWidth: 0.2,
    bladeLength: 0.5,
    bladeWidth: 0.15,
    bladeThickness: 0.02,
    pommelSize: 0.03,
    handleColor: '#212121',
    metalColor: '#eceff1',
    guardColor: '#ffab00',
    roughness: 0.2,
    metalness: 0.9,
    effect: WeaponEffect.NONE,
    effectColor: '#ffffff',
    handleTexture: TextureStyle.CLOTH,
    bladeTexture: TextureStyle.NONE
  },
  "Cleric's Mace": {
    type: WeaponType.MACE,
    handleLength: 0.6,
    handleRadius: 0.035,
    guardWidth: 0.1,
    bladeLength: 0.2,
    bladeWidth: 0.2,
    bladeThickness: 0.2,
    pommelSize: 0.05,
    handleColor: '#5d4037',
    metalColor: '#b0bec5',
    guardColor: '#b0bec5',
    roughness: 0.5,
    metalness: 0.5,
    effect: WeaponEffect.NONE,
    effectColor: '#ffffff',
    handleTexture: TextureStyle.WOOD,
    bladeTexture: TextureStyle.RUST
  },
  "Rogue's Fang": {
    type: WeaponType.DAGGER,
    handleLength: 0.2,
    handleRadius: 0.02,
    guardWidth: 0.1,
    bladeLength: 0.3,
    bladeWidth: 0.05,
    bladeThickness: 0.01,
    pommelSize: 0.03,
    handleColor: '#1a1a1a',
    metalColor: '#263238',
    guardColor: '#37474f',
    roughness: 0.6,
    metalness: 0.5,
    effect: WeaponEffect.NONE,
    effectColor: '#ffffff',
    handleTexture: TextureStyle.CLOTH,
    bladeTexture: TextureStyle.DAMASCUS
  },
  "Ceremonial Kris": {
    type: WeaponType.DAGGER,
    handleLength: 0.25,
    handleRadius: 0.025,
    guardWidth: 0.15,
    bladeLength: 0.4,
    bladeWidth: 0.08,
    bladeThickness: 0.015,
    pommelSize: 0.04,
    handleColor: '#3e2723',
    metalColor: '#ffeb3b', // Gold-ish
    guardColor: '#ff6f00',
    roughness: 0.2,
    metalness: 1.0,
    effect: WeaponEffect.NONE,
    effectColor: '#ffffff',
    variant: 'wavy',
    handleTexture: TextureStyle.SCALES,
    bladeTexture: TextureStyle.DAMASCUS
  },
  "Shinobi Thrower": {
    type: WeaponType.KUNAI,
    handleLength: 0.05,
    handleRadius: 0.01,
    guardWidth: 0.0,
    bladeLength: 0.25,
    bladeWidth: 0.06,
    bladeThickness: 0.01,
    pommelSize: 0.03, // Ring
    handleColor: '#e0e0e0', // Bandages
    metalColor: '#424242',
    guardColor: '#424242',
    roughness: 0.7,
    metalness: 0.4,
    effect: WeaponEffect.NONE,
    effectColor: '#ffffff',
    handleTexture: TextureStyle.CLOTH,
    bladeTexture: TextureStyle.RUST
  },
  "Shadow Spike": {
    type: WeaponType.KUNAI,
    handleLength: 0.3, // Longer handle
    handleRadius: 0.01, // Thin
    guardWidth: 0.0,
    bladeLength: 0.5, // Long blade
    bladeWidth: 0.03, // Thin blade
    bladeThickness: 0.01,
    pommelSize: 0.05,
    handleColor: '#111111',
    metalColor: '#1a1a1a', // Dark metal
    guardColor: '#00ff00', // Neon accents
    roughness: 0.2,
    metalness: 0.9,
    effect: WeaponEffect.GLOW,
    effectColor: '#00ff00', // Green Glow
    handleTexture: TextureStyle.NONE,
    bladeTexture: TextureStyle.COSMIC
  },
  "Sun Disc": {
    type: WeaponType.CHAKRAM,
    handleLength: 0, 
    handleRadius: 0.02,
    guardWidth: 0,
    bladeLength: 0.6, 
    bladeWidth: 0.15, 
    bladeThickness: 0.01,
    pommelSize: 0,
    handleColor: '#ff6f00',
    metalColor: '#ffca28',
    guardColor: '#ffca28',
    roughness: 0.2,
    metalness: 0.9,
    effect: WeaponEffect.FIRE,
    effectColor: '#ff9800',
    handleTexture: TextureStyle.NONE,
    bladeTexture: TextureStyle.DAMASCUS
  },
  "Moon Ring": {
    type: WeaponType.CHAKRAM,
    handleLength: 0,
    handleRadius: 0.015,
    guardWidth: 0,
    bladeLength: 0.5,
    bladeWidth: 0.08,
    bladeThickness: 0.005,
    pommelSize: 0,
    handleColor: '#b0bec5',
    metalColor: '#e3f2fd',
    guardColor: '#e3f2fd',
    roughness: 0.1,
    metalness: 0.8,
    effect: WeaponEffect.GLOW,
    effectColor: '#40c4ff',
    handleTexture: TextureStyle.NONE,
    bladeTexture: TextureStyle.COSMIC
  },
  "Claymore": {
    type: WeaponType.SWORD,
    handleLength: 0.5,
    handleRadius: 0.035,
    guardWidth: 0.5,
    bladeLength: 1.5,
    bladeWidth: 0.12,
    bladeThickness: 0.03,
    pommelSize: 0.06,
    handleColor: '#5d4037',
    metalColor: '#90a4ae',
    guardColor: '#78909c',
    roughness: 0.5,
    metalness: 0.6,
    effect: WeaponEffect.NONE,
    effectColor: '#ffffff',
    handleTexture: TextureStyle.LEATHER,
    bladeTexture: TextureStyle.NONE
  },
  "Katana": {
    type: WeaponType.SWORD,
    handleLength: 0.4,
    handleRadius: 0.025,
    guardWidth: 0.08, // Tsuba
    bladeLength: 1.1,
    bladeWidth: 0.06,
    bladeThickness: 0.015,
    pommelSize: 0.03,
    handleColor: '#212121',
    metalColor: '#eceff1',
    guardColor: '#ffd700',
    roughness: 0.1,
    metalness: 0.9,
    effect: WeaponEffect.NONE,
    effectColor: '#ffffff',
    variant: 'katana',
    handleTexture: TextureStyle.CLOTH,
    bladeTexture: TextureStyle.DAMASCUS
  },
  "Rapier": {
    type: WeaponType.SWORD,
    handleLength: 0.25,
    handleRadius: 0.02,
    guardWidth: 0.2,
    bladeLength: 1.2,
    bladeWidth: 0.025,
    bladeThickness: 0.01,
    pommelSize: 0.04,
    handleColor: '#8d6e63',
    metalColor: '#cfd8dc',
    guardColor: '#ffcc80',
    roughness: 0.1,
    metalness: 0.8,
    effect: WeaponEffect.NONE,
    effectColor: '#ffffff',
    variant: 'rapier',
    handleTexture: TextureStyle.LEATHER,
    bladeTexture: TextureStyle.NONE
  },
  "Battleaxe": {
    type: WeaponType.AXE,
    handleLength: 1.2,
    handleRadius: 0.04,
    guardWidth: 0.1,
    bladeLength: 0.6,
    bladeWidth: 0.35,
    bladeThickness: 0.06,
    pommelSize: 0.07,
    handleColor: '#3e2723',
    metalColor: '#455a64',
    guardColor: '#263238',
    roughness: 0.7,
    metalness: 0.5,
    effect: WeaponEffect.NONE,
    effectColor: '#ffffff',
    handleTexture: TextureStyle.WOOD,
    bladeTexture: TextureStyle.RUST
  },
  "Tomahawk": {
    type: WeaponType.AXE,
    handleLength: 0.4,
    handleRadius: 0.025,
    guardWidth: 0.05,
    bladeLength: 0.2,
    bladeWidth: 0.15,
    bladeThickness: 0.02,
    pommelSize: 0.03,
    handleColor: '#8d6e63',
    metalColor: '#b0bec5',
    guardColor: '#5d4037',
    roughness: 0.5,
    metalness: 0.6,
    effect: WeaponEffect.NONE,
    effectColor: '#ffffff',
    handleTexture: TextureStyle.WOOD,
    bladeTexture: TextureStyle.NONE
  },
  "Glaive": {
    type: WeaponType.SPEAR,
    handleLength: 1.5,
    handleRadius: 0.03,
    guardWidth: 0.1,
    bladeLength: 0.7, // Long blade
    bladeWidth: 0.15,
    bladeThickness: 0.02,
    pommelSize: 0.04,
    handleColor: '#33691e',
    metalColor: '#e0e0e0',
    guardColor: '#fdd835',
    roughness: 0.3,
    metalness: 0.8,
    effect: WeaponEffect.NONE,
    effectColor: '#ffffff',
    handleTexture: TextureStyle.WOOD,
    bladeTexture: TextureStyle.NONE
  },
  "Warhammer": {
    type: WeaponType.MACE,
    handleLength: 0.8,
    handleRadius: 0.04,
    guardWidth: 0.1,
    bladeLength: 0.3, // Heavy head
    bladeWidth: 0.1, // stubby spikes
    bladeThickness: 0.2, // Boxy
    pommelSize: 0.06,
    handleColor: '#424242',
    metalColor: '#37474f',
    guardColor: '#37474f',
    roughness: 0.6,
    metalness: 0.6,
    effect: WeaponEffect.NONE,
    effectColor: '#ffffff',
    handleTexture: TextureStyle.LEATHER,
    bladeTexture: TextureStyle.RUST
  },
  "Morningstar": {
    type: WeaponType.MACE,
    handleLength: 0.6,
    handleRadius: 0.03,
    guardWidth: 0.1,
    bladeLength: 0.15, // Small ball
    bladeWidth: 0.3, // Long spikes
    bladeThickness: 0.05,
    pommelSize: 0.05,
    handleColor: '#5d4037',
    metalColor: '#212121',
    guardColor: '#212121',
    roughness: 0.8,
    metalness: 0.4,
    effect: WeaponEffect.NONE,
    effectColor: '#ffffff',
    handleTexture: TextureStyle.WOOD,
    bladeTexture: TextureStyle.RUST
  },
  "Gladius": {
    type: WeaponType.SWORD,
    handleLength: 0.2,
    handleRadius: 0.03,
    guardWidth: 0.2,
    bladeLength: 0.6,
    bladeWidth: 0.08,
    bladeThickness: 0.02,
    pommelSize: 0.05,
    handleColor: '#f4e7d1', // Bone handle
    metalColor: '#cfd8dc',
    guardColor: '#8d6e63',
    roughness: 0.4,
    metalness: 0.7,
    effect: WeaponEffect.NONE,
    effectColor: '#ffffff',
    handleTexture: TextureStyle.NONE,
    bladeTexture: TextureStyle.NONE
  }
};